### PR TITLE
Refactor get_model() function to support multiple models

### PR DESCRIPTION
**Pull request by Mideky-hub**
It will allow use to easly incorporate more models as the request increase.

When you want to add a model: 
- If this is with a new framework, then add the fw to args_mapping, with the ChatFW func and the args you have to put in.
- Then add the name of the model with the framework associated to the model_mapping dictionary.

That's it! Simplier, prettier, cleaner.

To complete that I will refactor the load_api_key() in order to pass though parameter the model to associate the key search to template model and therefore not having one "main" model but a universal application which you can use which ever model to help you.

### CODE REVIEW

**Comment by Mideky-hub** [comment]
Another thing to see here is that we can incorporte a APIGetter class to easily adapt to model change with a practical template that adapt when a request is triggered.

**Comment by Mideky-hub** [comment]
If merged, then I'll be integrating multiple models.

**Review by onuratakan — APPROVED** [review]
Super nice

**Comment by onuratakan** [comment]
Thank you so much.

**Comment by Mideky-hub** [comment]
You're welcome! That's a pleasure!

**Pull request merged**
