### PR TITLE
Llama3 & Gemini Pro support

### LINKED ISSUE #84: Adding Gemini 1.5-Pro/Flash
Hi, any plans to add Google's LLMs? Both are multimodal and have a very useful free tier for the API, so a lot of people use it.

### LINKED ISSUE #87: Add llama3 integration ?
are you going to add llama3 ?

### PR DESCRIPTION
**Pull request by Mideky-hub**
Avoid having not up-to-date packages

### CODE REVIEW

**Comment by onuratakan** [comment]
Amazing.

**Comment by onuratakan** [comment]
I will seperate the api key save section.

**Comment by Mideky-hub** [comment]
Sure, thank you to you, you got great work! It's nice to work on this project! I will soon review the load API key function to have standardized way to compile everything. Maybe having a ModelFactory to generate model easily as indicate another issue in order to let the user add the model they want more easily? This can help us by having only 3-4 generic model and letting the user import their own model to have presets that they can share with each other etc..  what do you think about that @onuratakan ?

**Comment by onuratakan** [comment]
> Sure, thank you to you, you got great work! It's nice to work on this project! I will soon review the load API key function to have standardized way to compile everything. Maybe having a ModelFactory to generate model easily as indicate another issue in order to let the user add the model they want more easily? This can help us by having only 3-4 generic model and letting the user import their own model to have presets that they can share with each other etc.. what do you think about that @onuratakan ?

Thanks, i think we should give an ability to customize llm like

```python
from gpt_computer_assistant import start

your_custom_langchain_llm = OpenAI()

start(your_custom_langchain_llm )

```

**Comment by onuratakan** [comment]
Also i think we should add click something on the screen ability. I just added it to roadmap. Just for your info

**Comment by Mideky-hub** [comment]
> > Sure, thank you to you, you got great work! It's nice to work on this project! I will soon review the load API key function to have standardized way to compile everything. Maybe having a ModelFactory to generate model easily as indicate another issue in order to let the user add the model they want more easily? This can help us by having only 3-4 generic model and letting the user import their own model to have presets that they can share with each other etc.. what do you think about that @onuratakan ?
> 
> Thanks, i think we should give an ability to customize llm like
> 
> ```python
> from gpt_computer_assistant import start
> 
> your_custom_langchain_llm = OpenAI()
> 
> start(your_custom_langchain_llm )
> ```

This could only work if the LLM is langchain coded, otherwise it will just throw error, is there an overlapping module that encapsulate langchain and another LLM-base that regroup/holds other LLMs?

**Comment by onuratakan** [comment]
> > > Sure, thank you to you, you got great work! It's nice to work on this project! I will soon review the load API key function to have standardized way to compile everything. Maybe having a ModelFactory to generate model easily as indicate another issue in order to let the user add the model they want more easily? This can help us by having only 3-4 generic model and letting the user import their own model to have presets that they can share with each other etc.. what do you think about that @onuratakan ?
> > 
> > 
> > Thanks, i think we should give an ability to customize llm like
> > ```python
> > from gpt_computer_assistant import start
> > 
> > your_custom_langchain_llm = OpenAI()
> > 
> > start(your_custom_langchain_llm )
> > ```
> 
> This could only work if the LLM is langchain coded, otherwise it will just throw error, is there an overlapping module that encapsulate langchain and another LLM-base that regroup/holds other LLMs?

Actualy the largest one is langchain. Also they add new llms.

**Review by onuratakan — APPROVED** [review]
Nice

**Pull request merged**
